### ISSUE TITLE
Do not trigger a build multiple times

### ISSUE THREAD

**Issue by dfuchss** [PalladioSimulator/Palladio-Build-ActionsPipeline#1]
@Nicolas-Boltz I would suggest to add this to the default workflow:

```yml
  pre_job:
    # No need to run that on the self hosted environment :)
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'

  build:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    ..... now the build follows here .....
```

This would check that a build will not be triggered multiple times (e.g., in a PR for the branch and for the PR)
See builds:

![image](https://user-images.githubusercontent.com/22198798/175039460-0f04c44d-932c-44b1-9713-9347aaa357bc.png)
